name: Java CI with Gradle

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Start SUT
        # Запускаем SUT,
        # имя файла SUT будет отличаться в каждой задаче.
        # & означает, что в фоновом режиме не блокируем терминал для запуска тестов,
        # обязательно должен быть для запуска SUT в CI
        run: java -jar ./artifacts/app-ibank.jar -P:profile=test &
      - name: Build with Gradle
        # Запускаем автотесты
        # Для проектов на базе Selenide необходимо добавить параметр для запуска браузера
        # в headless режиме -Dselenide.headless=true, параметр --info должен остаться
        run: ./gradlew test --info -Dselenide.headless=true

        #Для активации тестового режима при запуске SUT нужно указать флаг -P:profile=test, то есть: java -jar app-ibank.jar -P:profile=test
        #Важно: если вы не активируете тестовый режим, любые запросы на http://localhost:9999/api/system/users будут вам возвращать 404 Not Found.
